---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: ENV_NAMESPACE
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: backend
      sourceRef:
        kind: HelmRepository
        name: changeME
      version: 1.0.0
  values:
      backend_url: ENV_BACKEND_API_URL 
