---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: ENV_NAMESPACE
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: frontend
      sourceRef:
        kind: HelmRepository
        name: changeME
      version: 1.0.0